version: '3.8'
services:
  master:
    build:
      context: ./master
    ports:
      - "25000:25000"
    environment:
      - SECONDARY_URLS=http://secondary1:25001,http://secondary2:25002
    depends_on:
      - secondary1
      - secondary2

  secondary1:
    build:
      context: ./secondary
    environment:
      - PORT=25001
    ports:
      - "25001:25001"


  secondary2:
    build:
      context: ./secondary
    environment:
      - PORT=25002
    ports:
      - "25002:25002"
